version: '3'
services:

  number-api:
    build: number-api
    environment:
      LISTENERS_COUNT: $LISTENERS_COUNT
      BUFFER_SIZE: $BUFFER_SIZE
      JAVA_OPTS: "-Xmx200m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777"
      DEBUG_PORT: 7777
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9091"
    ports:
      - 8080
      - 7777
    image: number-api
    restart: "no"
    depends_on:
      number-generator:
        condition: service_started
      kafka:
        condition: service_healthy
    logging:
      options:
        max-size: "50m"
        max-file: "10"

  number-generator:
    build: number-generator
    environment:
      LISTENERS_COUNT: $LISTENERS_COUNT
      JAVA_OPTS: "-Xmx200m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777"
      DEBUG_PORT: 7777
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9091"
    ports:
      - 7777
    image: number-generator
    restart: "no"
    depends_on:
      range-generator:
        condition: service_started
      kafka:
        condition: service_healthy
    logging:
      options:
        max-size: "50m"
        max-file: "10"

  range-generator:
    build: range-generator
    environment:
      MAX_MESSAGES: $MAX_MESSAGES
      ENABLE_INIT_CONTROLLER: $ENABLE_INIT_CONTROLLER
      JAVA_OPTS: "-Xmx200m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777"
      DEBUG_PORT: 7777
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9091"
    ports:
      - 8080:8080
      - 7777:7777
    image: range-generator
    restart: "no"
    depends_on:
      kafka:
        condition: service_healthy
    logging:
      options:
        max-size: "50m"
        max-file: "10"

  zookeeper:
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
    mem_limit: 512m
    healthcheck:
      test: ["CMD-SHELL", "zkServer.sh", "status"]
      interval: 1s
      timeout: 5s
      retries: 180

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9091,EXTERNAL://${KAFKA_ADVERTISED_HOST_NAME:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPICS: "generation.ranges:5:1,unique.natural.number:5:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      zookeeper:
        condition: service_healthy
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 1s
      timeout: 5s
      retries: 180