server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: number-api
  main:
    banner-mode: off
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: number-api-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false

kafka:
  consumer-topic: unique.natural.number
  listeners-count: ${LISTENERS_COUNT:5}

buffer-size: ${BUFFER_SIZE:5}